### ISSUE TITLE
Improved model fit to very simple example

### ISSUE THREAD

**Issue by caseyzipfel** [grantbrown/ABSEIR#16]
Hi Grant! 
Thanks for a great package! I have found it very useful, and I am trying to improve my understanding of how to use the package most effectively.
I have been working with the package applied to a very simple simulated SEIR model so I can improve my understanding of how to work with the model when there are ground-truth epidemic parameters. 
First, I have attached a python notebook (simple_epidemic_simulation_for_ABSEIR.ipynb) with a very simple deterministic SEIR model to generate an incidence time series, where I know the epidemiological parameters. 
Second, I have attached R code (ABSEIR_with_simple_simulated_epidemic.R) with a very simple ABSEIR model to estimate epidemic parameters and evaluate fit. 
When I run the ABSEIR model with less informative priors on the transition probabilities(p_ei_ess = 10, p_ir_ess = 10) and the exposure process (betaPriorPrecision = 10), the resulting parameter estimates have larger variance, and the peak is shifted a bit earlier and lower than the actual cases (less_informative_prior_time_series.png and less_informative_prior_estimates.png). I can increase the confidence on the priors (p_ei_ess = 1000, p_ir_ess = 1000, betaPriorPrecision = 1000) to get less variance in the estimates (more_informative_prior_estimates.png), but the simulated time series remains similar to prior model (more_informative_prior_time_series.png). With such a simple and perfect epidemic time series, I would anticipate that the fitted time series should be much more similar to the data. Is there a way to improve this fit? Do you have any other feedback on how I've set up my simple ABSEIR model? I am planning to apply this to a much more complex model, so I want to ensure my application to this simple example can help me fully understand how to most effectively use the package. 
Another question that I've had for when I am able to apply this to a more complex question- do you have a recommendation for the scaling of the distance matrix for between-location transmission? For example, in the measles example vignette, you give examples of a CAR model of 0s and 1s, and a gravity model where the mean value is 0.02, and these obviously give different results. My guess was that the actual values in the matrix did not matter as much as the relative relationship between the values, since the matrix is multiplied by rho, which is estimated in the model, to scale those values up or down appropriately. But, I tried the measles example with gravity model given, and then with the entire gravity matrix multiplied by 1000, and this gave very different results. So, the scale of the distance matrix values seems to matter, but it is unclear to me what is appropriate. For example, if I wanted a distance matrix based on traveling data, say a matrix based upon the proportion of the population that travels between location a and location b, relative to the population of location a, do you have a recommendation about how to appropriately scale this?
Let me know if any aspects of my question are not clear. Thank you in advance!

[simple_ABSEIR_example.zip](https://github.com/grantbrown/ABSEIR/files/5881623/simple_ABSEIR_example.zip)

**Comment by grantbrown** [comment]
As far as the scaling of distance matrices goes, it's a bit of an unsolved problem. A safe bet is to transform the matrices to be row-stochastic, but in principal other structures which capture the proportionality of the contact rate/intensity could be meaningful. 

As for your first question, I think part of it is just a limitation of simulation-based techniques. The parameters you specify are often weakly identified to begin with, and we're trying to make inference here based solely on the similarity between generated data and the observations rather than relying on the structure of a likelihood.

As far as the model fit goes, while I haven't had a chance to examine your work in detail, it sounds like you're using a stochastic model to fit a curve generated deterministically. This is likely to be the source of some of the differences you observe - especially when the epidemic is small, the characteristics will simply be different. Try a stochastic simulation to see if you can capture more reasonable model fits.
