### ISSUE TITLE
Interpretation of Beta_SE coefficients

### ISSUE THREAD

**Issue by caseyzipfel** [grantbrown/ABSEIR#17]
Hi Grant! 
Sorry for the multiple questions! 
I was wondering if you could provide me with some insight about how to interpret the Beta_SE's resulting from a model. Can these be interpreted similar to a GLM, where a significantly positive or negative coefficient indicates a positive or negative effect on the response? For example, if the covariate was vaccination rates, would I expect to find a negative Beta_SE, indicating that higher levels of vaccination results in a decrease in transmission and fewer cases? 
Thank you!

**Comment by grantbrown** [comment]
Hi Casey, sorry for the delay - your previous question got lost in the shuffle. 

As far as coefficient interpretation, they can indeed be interpreted somewhat like a GLM. Instead of being linked to a mean structure, they're linked to the contact intensity, which combines the infectiousness of the pathogen and the contact rate. If you include vaccination rates as a static variable (not changing over time for each place), then the parameter should tell you how changes in vaccination are associated with changes in epidemic intensity. If you want to formalize the impact of the parameters, one way would be to do posterior predictive simulations while modifying the covariates. For example, after fitting the model you could do simulations where you modify the vaccination rates to see what the predicted change would be.
